name: PlantEst
channels:
  - open3d-admin
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=2.2.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - babel=2.9.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.3.0
  - brotlipy=0.7.0
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - cryptography=3.4.5
  - decorator=4.4.2
  - defusedxml=0.7.1
  - entrypoints=0.3
  - hdbscan=0.8.27
  - idna=2.10
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.21.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.17.0
  - jinja2=2.11.3
  - joblib=1.0.1
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-packaging=0.7.12
  - jupyter_client=6.1.7
  - jupyter_core=4.7.1
  - jupyter_server=1.4.1
  - jupyterlab=3.0.10
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.3.0
  - jupyterlab_widgets=1.0.0
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - liblapack=3.8.0
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - nb_conda_kernels=2.3.1
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - notebook=6.2.0
  - numpy=1.19.2
  - numpy-base=1.19.2
  - open3d=0.11.2
  - openssl=1.1.1k
  - packaging=20.9
  - pandoc=2.11
  - pandocfilters=1.4.3
  - parso=0.8.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.0.1
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.8.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.8
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - pyzmq=20.0.0
  - readline=8.1
  - requests=2.25.1
  - scikit-learn=0.24.1
  - send2trash=1.5.0
  - setuptools=52.0.0
  - six=1.15.0
  - sniffio=1.2.0
  - sqlite=3.33.0
  - terminado=0.9.2
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - urllib3=1.26.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - pip:
    - addict==2.4.0
    - argparse==1.4.0
    - astroid==2.5.2
    - cycler==0.10.0
    - dt-apriltags==3.1.1
    - imageio==2.9.0
    - isort==5.8.0
    - jsonpatch==1.32
    - jsonpointer==2.1
    - jupyter-console==6.4.0
    - kiwisolver==1.3.1
    - lazy-object-proxy==1.6.0
    - linecache2==1.0.0
    - matplotlib==3.3.4
    - mccabe==0.6.1
    - networkx==2.5.1
    - opencv-python==4.5.2.54
    - pandas==1.2.3
    - pillow==8.1.2
    - plyfile==0.7.3
    - protobuf==3.15.7
    - pymesh==1.0.2
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - qtconsole==5.0.3
    - qtpy==1.9.0
    - scikit-image==0.18.1
    - scipy==1.6.1
    - sklearn==0.0
    - tifffile==2021.3.31
    - toml==0.10.2
    - torchfile==0.1.0
    - tqdm==4.59.0
    - traceback2==1.4.0
    - trimesh==3.9.20
    - typing-extensions==3.7.4.3
    - unittest2==1.1.0
    - visdom==0.1.8.9
    - websocket-client==1.0.1
    - wrapt==1.12.1
