

show_raw: False

downsample_div: 300

hdbscan:
  min_cluster_size: 300 # 300 for luca2, 200 for palm , 150 for avo6, smaller for field
  gen_min_span_tree: True
  cluster_selection_method: 'leaf' # 'eom' or 'leaf'
  min_samples: 5
  hdbscan_debug: False

show_extracted_clusters: False
