# parameters for hdbscan

path: '/home/soley/3D-data/filtered_avocado.ply'
#path: '/home/soley/3D-data/filtered_luca2.ply'
#path: '/home/soley/3D-data/filtered_field.ply'
#path: '/home/soley/3D-data/filtered_palm.ply'

show_raw: False

downsample_div: 300

hdbscan:
  min_cluster_size: 300 # 300 for avo, luca and palm, needs to be smaller for field
  gen_min_span_tree: True
  cluster_selection_method: 'leaf' # 'eom' or 'leaf'
  min_samples: 5
  hdbscan_debug: True

show_extracted_clusters: False