pathRoot = "../data/avo_6/"#'../../3D-data/
pathRoot2 = "../data/avo_6"
pathOrgans= "../data/organs/"
pathOrganClass= "../organTraining/"
#holeMeshName = "fused.ply"
#croppedPcdRawName = 'cropped_pcd_raw_avocado.ply'
croppedPcdFilteredName = 'dense/cropped_fused.ply'
#croppedMeshName = "dense/cropped_avo6.ply"
croppedMeshName = "dense/cropped_avocado_fused_35.ply"
MeshOrigName = "dense/orig_fused.ply"
#croppedMeshName = "dense/cropped_avo6.ply"
hdbscanPath = "./cluster/config/hdbscan_config.yaml"
colmapFolderName = ""
apriltagSide = 17.3
nb_points=20
radius=0.1