pathRoot = "../data/avo_6/"
pathRoot2 = "../data/avo_6"
pathOrgans= "../data/organs/"
pathOrganClass= "../organTraining/"
croppedPcdFilteredName = 'dense/cropped_fused.ply'
hdbscanPath = "./cluster/config/hdbscan_config.yaml"
colmapFolderName = ""
apriltagSide = 17.3
nb_points=20
radius=0.1